### ISSUE TITLE
MD5 is used when SHA-1 should be used instead

### ISSUE THREAD

**Issue by frioux** [rjbs/Data-UUID#10] opened 2014-07-07 14:48 UTC
See https://en.wikipedia.org/wiki/UUID#Version_5_.28SHA-1_hash.29

**Comment by sparvu** [comment] 2015-02-13 16:11
Can we have support for v5 in Data::UUID ?

**Comment by rjbs** [comment] 2015-08-01 22:46
duplicate of https://github.com/rjbs/Data-UUID/issues/16 ( which is later but has a better subject )

**Closed by rjbs** 2015-08-01 22:46 UTC
